project13/app1/urls.py
from app1.views import *

from django.urls import path
app_name='somethingsomething'

urlpatterns=[
    path('farha/',farha,name='farha'),
]

project13/app2/urls.py
from app2.views import *
from django.urls import path
app_name='second'

urlpatterns=[
    path('response/',response,name='response'),
]

project13/project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

project13/app1/models.py
from django.db import models

# Create your models here.

project13/app2/models.py
from django.db import models

# Create your models here.

project13/app1/views.py
from django.shortcuts import render

# Create your views here.

def farha(request):
    return render(request,'farha.html')

project13/app2/views.py
from django.shortcuts import render

# Create your views here.


def response(request):
    return render(request,'response.html')

project13/templates/farha.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>iam farahana</h1>
        <h1>iam in jspiders</h1>
        <h1>i want a job</h1>
        <a href="{% url 'second:response' %}"/>
    </center>
</body>
</html>

project13/templates/response.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is good</h1>
    </center>
</body>
</html>